---
title: "Data Science"
author: "Vignesh J Muralidharan"
date: "March 19, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse);library(factoextra);library(cluster) 
library(NbClust) ;library(fpc);library(dendroextras)
library(dendextend);library(mclust);library(dbscan) 
library(dplyr);library(plyr);library(dataQualityR)
library(e1071) ;library(mice);library(Amelia)
library(missForest);library(Hmisc);library(mi)
```

```{r}
data2013=read.csv("https://raw.githubusercontent.com/vigneshjmurali/Data-Science-Comp/master/Datasets/training2013.csv")
dim(data2013)
str(data2013)
#IMPUTATION PROCESS
is.null(data2013)
#for periods converting to NA first and then from NA's to the number 
data2013$SATREAD=revalue(data2013$SATREAD,c("."="NA"))
data2013$SATMATH=revalue(data2013$SATMATH,c("."="NA"))
data2013$ACTCUM=revalue(data2013$ACTCUM,c("."="NA"))
#b=table(data2013$SATREAD);View(b)
data2013$SATREAD=revalue(data2013$SATREAD,c("NA"="550"))
#c=table(data2013$SATMATH);View(c)
data2013$SATMATH=revalue(data2013$SATMATH,c("NA"="540"))
#d=table(data2013$ACTCUM);View(d)
data2013$ACTCUM=revalue(data2013$ACTCUM,c("NA"="25"))

#converting all NA's to 0 in all variables
data2013[is.na(data2013)]<-0

str(data2013)
data2013_y1<-data.frame(data2013[,c(1:27)])
data2013_y2<-data.frame(data2013[,c(1:26,28)])
data2013_y3<-data.frame(data2013[,c(1:26,29)])

#View(data2013)
#str(data2013)
#View(data2013)
#write.csv(data2013,"data2013.csv")
write.csv(data2013_y1,"data2013_y1.csv")
write.csv(data2013_y2,"data2013_y2.csv")
write.csv(data2013_y3,"data2013_y3.csv")
```

```{r}
plot(data2013_y2$NUID,data2013_y2$FRACDEGRE)
```


```{r}
data2015=read.csv("https://raw.githubusercontent.com/vigneshjmurali/Data-Science-Comp/master/Datasets/training2015.csv")
str(data2015)
sapply(data2015, function(x) sum(length(which(is.na(x)))))
#converting all NA's to 0 in all variables
#for periods converting to NA first and then from NA's to the number 
data2015$TUITINS=revalue(data2015$TUITINS,c("."="0"))
data2015$FEEINS=revalue(data2015$FEEINS,c("."="0"))
data2015$TUITOUT=revalue(data2015$TUITOUT,c("."="0"))
data2015$FEEOUT=revalue(data2015$FEEOUT,c("."="0"))

data2015[is.na(data2015)]<-0
str(data2015)
data2015_y1<-data.frame(data2015[,c(1:27)])
str(data2015_y1)
data2015_y2<-data.frame(data2015[,c(1:26,28)])
data2015_y3<-data.frame(data2015[,c(1:26,29)])
write.csv(data2015_y1,"data2015_y1.csv")
write.csv(data2015_y2,"data2015_y2.csv")
write.csv(data2015_y3,"data2015_y3.csv")
#write.csv(data2015,"data2015.csv")
plot(data2015_y2$NUID,data2015_y2$FRACDEGRE)
new<-read.csv("DSC_edit.csv")
plot(new$NUID,new$FRACDEGRE_15)
```

```{r}
data2014=read.csv("https://raw.githubusercontent.com/vigneshjmurali/Data-Science-Comp/master/Datasets/training2014.csv")
dim(data2014)
str(data2014)
sapply(data2014, function(x) sum(length(which(is.na(x))))) 
#converting all NA's to 0 in all variables
data2014[is.na(data2014)]<-0
data2014_y1<-data.frame(data2014[,c(1:30)])
data2014_y2<-data.frame(data2014[,c(1:29,31)])
data2014_y3<-data.frame(data2014[,c(1:29,32)])
write.csv(data2014_y1,"data2014_y1.csv")
write.csv(data2014_y2,"data2014_y2.csv")
write.csv(data2014_y3,"data2014_y3.csv")
#write.csv(data2014,"data2014.csv")
plot(data2014_y2$NUID,data2014_y2$FRACDEGRE)
```

```{r}
data2016=read.csv("https://raw.githubusercontent.com/vigneshjmurali/Data-Science-Comp/master/Datasets/training2016.csv")
str(data2016)
data2016$TUITINS=revalue(data2016$TUITINS,c("."="0"))
data2016$FEEINS=revalue(data2016$FEEINS,c("."="0"))
data2016$TUITOUT=revalue(data2016$TUITOUT,c("."="0"))
data2016$FEEOUT=revalue(data2016$FEEOUT,c("."="0"))
data2016[is.na(data2016)]<-0
data2016_y1<-data.frame(data2016[,c(1:30)])
data2016_y2<-data.frame(data2016[,c(1:29,31)])
data2016_y3<-data.frame(data2016[,c(1:29,32)])
write.csv(data2016_y1,"data2016_y1.csv")
write.csv(data2016_y2,"data2016_y2.csv")
write.csv(data2016_y3,"data2016_y3.csv")
#write.csv(data2016,"data2016.csv")
plot(data2016_y2$NUID,data2016_y2$FRACDEGRE)
```
```{r}
new<-read.csv("DSC_edit.csv")
plot(new$NUID,new$FRACDEGRE_16)
```


```{r}
prediction_13=read.csv("https://raw.githubusercontent.com/vigneshjmurali/Data-Science-Comp/master/Datasets/prediction2013.csv")
str(prediction_13)
#IMPUTATION PROCESS
is.null(prediction_13)
#for periods converting to NA first and then from NA's to the number 
prediction_13$SATREAD=revalue(prediction_13$SATREAD,c("."="NA"))
prediction_13$SATMATH=revalue(prediction_13$SATMATH,c("."="NA"))
prediction_13$ACTCUM=revalue(prediction_13$ACTCUM,c("."="NA"))

prediction_13$SATREAD=revalue(prediction_13$SATREAD,c("NA"="550"))
#c=table(data2013$SATMATH);View(c)
prediction_13$SATMATH=revalue(prediction_13$SATMATH,c("NA"="560"))
#d=table(data2013$ACTCUM);View(d)
prediction_13$ACTCUM=revalue(prediction_13$ACTCUM,c("NA"="26"))

#converting all NA's to 0 in all variables
prediction_13[is.na(prediction_13)]<-0
str(prediction_13)
prediction_13y1<-data.frame(prediction_13[,c(1:27)])
prediction_13y2<-data.frame(prediction_13[,c(1:26,28)])
prediction_13y3<-data.frame(prediction_13[,c(1:26,29)])
write.csv(prediction_13y1,"prediction_13y1.csv")
write.csv(prediction_13y2,"prediction_13y2.csv")
write.csv(prediction_13y3,"prediction_13y3.csv")
```

```{r}
prediction_14=read.csv("https://raw.githubusercontent.com/vigneshjmurali/Data-Science-Comp/master/Datasets/prediction2014.csv")
str(prediction_14)
sapply(prediction_14, function(x) sum(length(which(is.na(x))))) 
#converting all NA's to 0 in all variables
prediction_14[is.na(prediction_14)]<-0
prediction_14y1<-data.frame(prediction_14[,c(1:30)])
prediction_14y2<-data.frame(prediction_14[,c(1:29,31)])
prediction_14y3<-data.frame(prediction_14[,c(1:29,32)])
write.csv(prediction_14y1,"prediction_14y1.csv")
write.csv(prediction_14y2,"prediction_14y2.csv")
write.csv(prediction_14y3,"prediction_14y3.csv")
```

```{r}
prediction_15=read.csv("https://raw.githubusercontent.com/vigneshjmurali/Data-Science-Comp/master/Datasets/prediction2015.csv")
str(prediction_15)
sapply(prediction_15, function(x) sum(length(which(is.na(x)))))
#converting all NA's to 0 in all variables
prediction_15[is.na(prediction_15)]<-0
str(prediction_15)
prediction_15y1<-data.frame(prediction_15[,c(1:27)])
prediction_15y2<-data.frame(prediction_15[,c(1:26,28)])
prediction_15y3<-data.frame(prediction_15[,c(1:26,29)])
write.csv(prediction_15y1,"prediction_15y1.csv")
write.csv(prediction_15y2,"prediction_15y2.csv")
write.csv(prediction_15y3,"prediction_15y3.csv")
```

```{r}
prediction_16=read.csv("https://raw.githubusercontent.com/vigneshjmurali/Data-Science-Comp/master/Datasets/prediction2016.csv")
str(prediction_16)
sapply(prediction_16, function(x) sum(length(which(is.na(x))))) 
#converting all NA's to 0 in all variables
prediction_16[is.na(prediction_16)]<-0
prediction_16y1<-data.frame(prediction_16[,c(1:30)])
prediction_16y2<-data.frame(prediction_16[,c(1:29,31)])
prediction_16y3<-data.frame(prediction_16[,c(1:29,32)])
write.csv(prediction_16y1,"prediction_16y1.csv")
write.csv(prediction_16y2,"prediction_16y2.csv")
write.csv(prediction_16y3,"prediction_16y3.csv")
```
#=======================
#MULTIPLE IMPUTATION <https://medium.com/coinmonks/dealing-with-missing-data-using-r-3ae428da2d17>
#======================
```{r}
mult2013=read.csv("https://raw.githubusercontent.com/vigneshjmurali/Data-Science-Comp/master/Datasets/training2013.csv")
dim(mult2013)
str(mult2013)
#IMPUTATION PROCESS
is.null(mult2013)
#for periods converting to NA first and then from NA's to the number 
mult2013$SATREAD=revalue(mult2013$SATREAD,c("."="NA"))
mult2013$SATMATH=revalue(mult2013$SATMATH,c("."="NA"))
mult2013$ACTCUM=revalue(mult2013$ACTCUM,c("."="NA"))
str(mult2013)
#=================


imputed_2013<-mice(mult2013,m=3,maxit=10,method='cart',seed=500)
```

```{r}
library(factoextra)
library(ggplot2)
library(plyr)
library(caret)
library(ROCR)
library(crossval)
library(MASS)
library(e1071)
library(quantmod) 
library(nnet)
library(ggrepel)
```


##**Neural Network**
```{r}
# Bagging
as.matrix(data2013_y3)
set.seed(123)
ctrl <- trainControl(method = "cv", number=10,summaryFunction = twoClassSummary,
                     classProbs = TRUE,savePredictions = TRUE)
#expand.grid(.mtry=135, .ntree=c(1500, 2000, 2500))
bag.fit <- train(RETPCNT~., data=data2013_y3, method="treebag", trControl=ctrl)
```

```{r}
ptm<-proc.time()
NN.fit
#make prediction
NN.pred <- predict(NN.fit, newdata=prediction_13y3)

table(NN.pred, Y_test)
mean(NN.pred==Y_test)

# Plot ROC and AUC for KNN
#prob got from the predicted model
NN.probs <- predict(NN.fit, newdata=ad_test, type='prob')

NNPred <- prediction(NN.probs[,2], ad_test$Ad)
NNPerf <- performance(NNPred, "tpr", "fpr")
plot(NNPerf, colorize=TRUE)
abline(a=0, b=1, lty=2, lwd=2, col="black")
#AUC
AUC.NN<-performance(NNPred, "auc")

#Corresponding Performance Measures
NNPrediction <- factor(as.factor(NN.pred), c('nonad.', 'ad.'), labels = c("Not-Ad", "Ad"))
NNActual <- factor(as.factor(ad_test$Ad), c('nonad.', 'ad.'), labels = c("Not-Ad", "Ad"))

CMNN <- confusionMatrix(NNActual, NNPrediction, negative = "Not-Ad" )
DE.NN<-diagnosticErrors(CMNN)
DE.NN

proc.time()-ptm
```
```

